### ISSUE TITLE
Hello it doesn't work 

### ISSUE THREAD

**Issue by jpujol880807** [rishi-ramawat/laravel-postgresql-inherit#1]
After installed the package and add the provider in Laravel 5.4 trows this
[Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to undefined method Illuminate\Database\Schema\Blueprint::inherits()

**Comment by rishi-ramawat** [comment]
@jpujol880807 
+ Did you add 
    ```php
    RishiRamawat\PostgresSchema\PostgresqlSchemaServiceProvider::class,
    ```
    to the `providers` array in `config/app.php`?

+ Also make sure you use version `~2.2` for Laravel 5.4 and not `@dev-master`.
    * `@dev-master` has support for Laravel 5.3.
    * Laravel 5.4 support is on [laravel_5.4_support](https://github.com/rishi-ramawat/laravel-postgresql-inherit/tree/laravel_5.4_support) branch.

**Comment by jpujol880807** [comment]
hello this the require part of my composer.json
`"require": {
        "php": ">=5.6.4",
        "acacha/admin-lte-template-laravel": "4.*",
        "adldap2/adldap2-laravel": "^3.0",
        "babenkoivan/scout-elasticsearch-driver": "^1.1",
        "barryvdh/laravel-dompdf": "^0.8.0",
        "barryvdh/laravel-snappy": "^0.3.3",
        "doctrine/dbal": "~2.3",
        "elasticsearch/elasticsearch": "~5.0",
        "laravel/framework": "5.4.*",
        "laravel/scout": "^3.0",
        "laravel/tinker": "~1.0",
        "mpdf/mpdf": "^6.1",
        "pmatseykanets/laravel-scout-postgres": "^0.5.0",
        "rishi-ramawat/laravel-postgresql-inherit": "~2.2",
        "yajra/laravel-datatables-buttons": "^2.0",
        "yajra/laravel-datatables-oracle": "^7.5"
    },`

and here is my providers array section:
` /*
         * Package Service Providers...
         */
        Laravel\Tinker\TinkerServiceProvider::class,
        Adldap\Laravel\AdldapServiceProvider::class,
        Yajra\Datatables\DatatablesServiceProvider::class,
        Yajra\Datatables\ButtonsServiceProvider::class,
        Laravel\Scout\ScoutServiceProvider::class,
        ScoutEngines\Postgres\PostgresEngineServiceProvider::class,
        ScoutElastic\ScoutElasticServiceProvider::class,
        Barryvdh\DomPDF\ServiceProvider::class,
        Barryvdh\Snappy\ServiceProvider::class,
        RishiRamawat\PostgresSchema\PostgresqlSchemaServiceProvider::class,
        /*`

**Comment by rishi-ramawat** [comment]
@jpujol880807 Is the name of your database connection `pgsql`?

If not then you would have to add this to the `register()` method of your `AppServiceProvider.php` in **Laravel 5.4**.

```php
\Illuminate\Database\Connection::resolverFor('<postgres-db-connection-name>', function ($connection, $database, $prefix, $config) {
    return new \RishiRamawat\PostgresSchema\PostgresConnection($connection, $database, $prefix, $config);
});
```
